apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: healthcare-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: healthcare-role-binding
subjects:
- kind: ServiceAccount
  name: healthcare-sa
  namespace: workshop
roleRef:
  kind: ClusterRole
  name: healthcare-role
  apiGroup: rbac.authorization.k8s.io
