apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: mongo-secret

type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==  # base64 encoded 'root'
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=  #
