apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::851725361780:role/todo-eks-cluster-service-account-wasi
